include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*.mk))
include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*/*.mk))
include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*/*/*.mk))
include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*/*/*/*.mk))
include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*/*/*/*.mk))
include $(sort $(wildcard $(BR2_EXTERNAL_CFSOS_PATH)/package/*/*/*/*/*/*.mk))
